---
directories:
  forrest:
    url: 'https://raw.githubusercontent.com/startwind/forrest-directory/main/directory.yml'

repositories:
  # "friends-of-wp":
  #  adapter: gist
  #  name: "Friends of WP"
  #  description: "Some very helpful WordPress commands."
  #  config:
  #    username: "friends-of-wp"
  #    prefix: 'wpdev: '

  forrest:
    type: api
    official: true
    name: "Forrest Big Database"
    description: "The big database with all commands known by Forrest."
    config:
      endpoint: https://api.forrestcli.com/
