---
directories:
  forrest:
    url: 'https://raw.githubusercontent.com/startwind/forrest-directory/main/directory.yml'
  360monitoring:
    loader:
      type: github
      config:
        repository: forrest-directory
        user: leankoala-gmbh
        file: directory.yml
        token: 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

repositories:
  # "friends-of-wp":
  #  adapter: gist
  #  name: "Friends of WP"
  #  description: "Some very helpful WordPress commands."
  #  config:
  #    username: "friends-of-wp"
  #    prefix: 'wpdev: '

  forrest-linux:
    adapter: yaml
    name: 'Forrest Linux Repository'
    description: 'Some very helpful everyday Linux commands.'
    config:
      file: 'https://raw.githubusercontent.com/startwind/forrest-directory/main/repositories/forrest-linux.yml'
