---
name: File linting

on:
  pull_request:
    paths:
      - '**.y?ml'
  push:
    paths:
      - '**.y?ml'

permissions:
  contents: read

jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run yamllint
        run: |
          find . -path \*/vendor -prune -false -o -name \*.y\*ml |
          xargs yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" || true
